import { createClient } from 'npm:@supabase/supabase-js@2.49.8';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// ── Structured error logging to system_events ─────────────────────────────────
async function logEvent(supabase: ReturnType<typeof createClient>, payload: {
  event_type: string;
  severity: 'warning' | 'error' | 'critical';
  details: Record<string, unknown>;
}) {
  try {
    await supabase.from('system_events').insert({
      function_name: 'sync-offline-agri-consultations',
      event_type:    payload.event_type,
      severity:      payload.severity,
      payload:       payload.details,
      created_at:    new Date().toISOString(),
    });
  } catch { /* never block sync for logging */ }
}

interface OfflineFarmer {
  name: string;
  village: string;
  phone: string;
  crops: string[];
  notes: string;
}

interface OfflineConsultation {
  id: string;
  ts: string;
  farmer: OfflineFarmer;
  consultType: string;
  intake: Record<string, string>;
  result: {
    urgency: string;
    reasons: string[];
    immediateActions: string[];
    mediumTermActions: string[];
    referrals: { who: string; why: string; urgency: string }[];
    warnings: string[];
    homeCare: string[];
    doNot: string[];
  };
  synced: boolean;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    const { sync_key, navigator_user_id, consultations } = body;

    const expectedKey = Deno.env.get('AGRI_OFFLINE_SYNC_KEY');
    if (!expectedKey || sync_key !== expectedKey) {
      return new Response(JSON.stringify({ error: 'Invalid sync key' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const effectiveUserId =
      navigator_user_id ||
      Deno.env.get('AGRI_OFFLINE_DEFAULT_USER_ID') ||
      'offline-agri-advisor';

    if (!Array.isArray(consultations) || consultations.length === 0) {
      return new Response(JSON.stringify({ received: 0, synced: 0, failed: 0, results: [] }), {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
    );

    const results: { offline_id: string; status: 'synced' | 'failed'; error?: string }[] = [];

    for (const consult of consultations as OfflineConsultation[]) {
      try {
        const farmer = consult.farmer;

        let farmerId: string | null = null;

        const { data: existingFarmers } = await supabase
          .from('agriculture_farmers')
          .select('id')
          .eq('youth_user_id', effectiveUserId)
          .ilike('farmer_name', farmer.name.trim())
          .eq('village', farmer.village)
          .limit(1);

        if (existingFarmers && existingFarmers.length > 0) {
          farmerId = existingFarmers[0].id;
        } else {
          const { data: newFarmer, error: farmerError } = await supabase
            .from('agriculture_farmers')
            .insert({
              youth_user_id: effectiveUserId,
              farmer_name: farmer.name.trim(),
              village: farmer.village,
              phone: farmer.phone || null,
              crops: farmer.crops || [],
              notes: farmer.notes || null,
            })
            .select('id')
            .single();

          if (farmerError || !newFarmer) {
            throw new Error(`Failed to create farmer: ${farmerError?.message}`);
          }
          farmerId = newFarmer.id;
        }

        const intakeEntries = Object.entries(consult.intake || {})
          .filter(([, v]) => v?.trim())
          .map(([k, v]) => `${k}: ${v.trim()}`)
          .join(' | ');
        const problemSummary = intakeEntries || 'Offline structured intake consultation';

        const res = consult.result;
        const adviceText = [
          `URGENCY: ${(res?.urgency || 'medium').toUpperCase()}`,
          '',
          res?.reasons?.length
            ? `KEY FINDINGS:\n${res.reasons.map((r) => `• ${r}`).join('\n')}`
            : '',
          res?.immediateActions?.length
            ? `\nIMMEDIATE ACTIONS:\n${res.immediateActions
                .map((a, i) => `${i + 1}. ${a}`)
                .join('\n')}`
            : '',
          res?.mediumTermActions?.length
            ? `\nMEDIUM-TERM PLAN:\n${res.mediumTermActions.map((a) => `→ ${a}`).join('\n')}`
            : '',
          res?.doNot?.length ? `\nDO NOT:\n${res.doNot.map((d) => `✗ ${d}`).join('\n')}` : '',
          res?.homeCare?.length
            ? `\nGENERAL ADVICE:\n${res.homeCare.map((h) => `✓ ${h}`).join('\n')}`
            : '',
          '\n[Generated by offline rule-based engine — vAI Agriculture Advisor]',
        ]
          .filter(Boolean)
          .join('\n');

        const { data: existing } = await supabase
          .from('agriculture_consultations')
          .select('id')
          .eq('farmer_id', farmerId)
          .eq('youth_user_id', effectiveUserId)
          .ilike('youth_actions_taken', `%offline_id:${consult.id}%`)
          .limit(1);

        if (existing && existing.length > 0) {
          results.push({ offline_id: consult.id, status: 'synced' });
          continue;
        }

        const { error: consultError } = await supabase
          .from('agriculture_consultations')
          .insert({
            youth_user_id: effectiveUserId,
            farmer_id: farmerId,
            consultation_type: consult.consultType,
            problem_summary: problemSummary,
            ai_advice: adviceText,
            urgency_level: res?.urgency || 'medium',
            youth_actions_taken: `[offline_id:${consult.id}]`,
            conversation_history: [],
            follow_up_needed: false,
            follow_up_date: null,
            follow_up_notes: null,
            resolved: false,
            created_at: consult.ts,
          });

        if (consultError) {
          throw new Error(`Failed to insert consultation: ${consultError.message}`);
        }

        results.push({ offline_id: consult.id, status: 'synced' });
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error(`[sync-offline-agri] Failed for ${consult.id}:`, msg);
        results.push({ offline_id: consult.id, status: 'failed', error: msg });
        await logEvent(supabase, {
          event_type: 'sync_error',
          severity:   'error',
          details: {
            offline_id:  consult.id,
            user_id:     effectiveUserId,
            farmer:      consult.farmer?.name,
            error:       msg,
          },
        });
      }
    }

    const synced = results.filter((r) => r.status === 'synced').length;
    const failed = results.filter((r) => r.status === 'failed').length;

    // Log summary if any failures occurred
    if (failed > 0) {
      await logEvent(supabase, {
        event_type: 'sync_partial_failure',
        severity:   failed === consultations.length ? 'error' : 'warning',
        details: {
          user_id:  effectiveUserId,
          received: consultations.length,
          synced,
          failed,
        },
      });
    }

    return new Response(JSON.stringify({ received: consultations.length, synced, failed, results }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error('[sync-offline-agri] Unhandled error:', msg);
    // Best-effort log — supabase client may not be available if error was during init
    try {
      const sb = createClient(
        Deno.env.get('SUPABASE_URL') ?? '',
        Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      );
      await logEvent(sb, {
        event_type: 'unhandled_exception',
        severity:   'critical',
        details:    { error: msg },
      });
    } catch { /* ignore */ }
    return new Response(JSON.stringify({ error: msg }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});