// src/pages/PlaygroundTogetherPage.tsx
//
// "Use Claude Together" — multi-user collaborative chat rooms, available to
// every organization, each scoped to its own rooms only. Any org member can
// create/join a named room; leaders can remove a message (soft-delete,
// visible as a placeholder to everyone) or close a room. Assistant replies
// are generated by api/chat-room.js and inserted as a single row — all
// viewers see new messages via a Supabase Realtime subscription, not
// client-side streaming.
//
// Back to Basics Youth Education stays exempt from the usage quota below —
// keep in sync with src/lib/backToBasicsScope.ts.

import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import AppLayout from '../components/layout/AppLayout';
import { useAuth } from '../hooks/useAuth';
import { supabase } from '../lib/supabaseClient';
import { BACK_TO_BASICS_ORG_ID } from '../lib/backToBasicsScope';
import { Users, Plus, Send, Trash2, Lock, Bot, ArrowLeft, Loader2, MessageSquare, Pencil, Check, X, Image as ImageIcon, BookOpen, Download } from 'lucide-react';

const QUOTA_TOKENS    = 25000;
const QUOTA_WINDOW_MS = 3 * 60 * 60 * 1000; // 3 hours

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// Matches the leader-role set enforced by RLS (together_rooms_update /
// together_messages_update_moderate) — keep in sync with the migration.
const LEADER_ROLES = new Set(['teacher', 'site_leader', 'facilitator', 'leader', 'research_lead']);

interface TogetherRoom {
  id: string;
  name: string;
  created_by: string;
  created_by_name: string;
  status: 'active' | 'closed';
  model: string;
  created_at: string;
  closed_at: string | null;
  closed_by: string | null;
}

interface TogetherMessage {
  id: string;
  room_id: string;
  sender_id: string | null;
  sender_name: string;
  role: 'user' | 'assistant';
  content: string;
  image_url: string | null;
  created_at: string;
  deleted_at: string | null;
  deleted_by: string | null;
}

const PlaygroundTogetherPage: React.FC = () => {
  const { user, loading: authLoading } = useAuth();
  const navigate = useNavigate();

  const [authChecked, setAuthChecked] = useState(false);
  const [effectiveOrgId, setEffectiveOrgId] = useState<string | null>(null);
  const isMember = !!effectiveOrgId;
  const quotaExempt = effectiveOrgId === BACK_TO_BASICS_ORG_ID;
  const [quotaUsed, setQuotaUsed] = useState(0);

  const isLeader = !!user?.role && (LEADER_ROLES.has(user.role) || user.role === 'platform_administrator');
  const canDeleteRoom = (room: TogetherRoom) => isLeader || room.created_by === user?.id;

  const [view, setView] = useState<'list' | 'room'>('list');
  const [rooms, setRooms] = useState<TogetherRoom[]>([]);
  const [loadingRooms, setLoadingRooms] = useState(true);
  const [newRoomName, setNewRoomName] = useState('');
  const [creatingRoom, setCreatingRoom] = useState(false);
  const [editingRoomId, setEditingRoomId] = useState<string | null>(null);
  const [editingName, setEditingName] = useState('');
  const [renaming, setRenaming] = useState(false);

  const [activeRoom, setActiveRoom] = useState<TogetherRoom | null>(null);
  const [messages, setMessages] = useState<TogetherMessage[]>([]);
  const [loadingMessages, setLoadingMessages] = useState(false);
  const [input, setInput] = useState('');
  const [sending, setSending] = useState(false);
  const [claudeThinking, setClaudeThinking] = useState(false);
  const [roomError, setRoomError] = useState('');

  // ── Image sharing + book view ────────────────────────────────────────────
  const [uploadingImage, setUploadingImage] = useState(false);
  const [showBookModal, setShowBookModal] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const chatEndRef = useRef<HTMLDivElement>(null);
  const roomsChannelRef = useRef<ReturnType<typeof supabase.channel> | null>(null);
  const messagesChannelRef = useRef<ReturnType<typeof supabase.channel> | null>(null);

  // ── Org resolution ────────────────────────────────────────────────────────
  // Resolves the caller's effective organization (organization_id, falling
  // back to a join_code lookup) via the same DB function RLS uses
  // (get_my_effective_profile()), so this never drifts from what the
  // policies actually enforce. No org resolved → not usable, redirect away.
  useEffect(() => {
    if (authLoading) return;
    if (!user) { navigate('/home', { replace: true }); return; }
    supabase
      .rpc('get_my_effective_profile')
      .then(({ data }) => {
        const orgId = data?.[0]?.organization_id ?? null;
        setEffectiveOrgId(orgId);
        setAuthChecked(true);
        if (!orgId) navigate('/home', { replace: true });
      });
  }, [user, authLoading, navigate]);

  // ── Quota usage for last 3 hours (Back to Basics is exempt) ──────────────
  useEffect(() => {
    if (!authChecked || !user?.id || quotaExempt) return;
    const windowStart = new Date(Date.now() - QUOTA_WINDOW_MS);
    supabase
      .from('api_cost_log')
      .select('input_tokens, output_tokens')
      .eq('user_id', user.id)
      .eq('page', 'PlaygroundTogetherPage')
      .gte('logged_at', windowStart.toISOString())
      .then(({ data }) => {
        const total = (data ?? []).reduce(
          (sum, r) => sum + (r.input_tokens ?? 0) + (r.output_tokens ?? 0), 0
        );
        setQuotaUsed(total);
      });
  }, [authChecked, user?.id, quotaExempt]);

  // ── Room list: fetch + realtime ──────────────────────────────────────────
  const fetchRooms = async () => {
    setLoadingRooms(true);
    const { data } = await supabase
      .from('together_rooms')
      .select('*')
      .eq('status', 'active')
      .order('updated_at', { ascending: false });
    setRooms(data ?? []);
    setLoadingRooms(false);
  };

  useEffect(() => {
    if (!authChecked || !isMember) return;
    fetchRooms();

    const channel = supabase
      .channel('together-rooms-list')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'together_rooms' }, payload => {
        const room = payload.new as TogetherRoom;
        if (room.status === 'active') setRooms(prev => [room, ...prev]);
      })
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'together_rooms' }, payload => {
        const room = payload.new as TogetherRoom;
        setRooms(prev =>
          room.status === 'active'
            ? prev.some(r => r.id === room.id) ? prev.map(r => r.id === room.id ? room : r) : [room, ...prev]
            : prev.filter(r => r.id !== room.id)
        );
      })
      .on('postgres_changes', { event: 'DELETE', schema: 'public', table: 'together_rooms' }, payload => {
        const room = payload.old as TogetherRoom;
        setRooms(prev => prev.filter(r => r.id !== room.id));
      })
      .subscribe();
    roomsChannelRef.current = channel;

    return () => { supabase.removeChannel(channel); roomsChannelRef.current = null; };
  }, [authChecked, isMember]);

  // ── Room view: fetch messages + realtime ─────────────────────────────────
  useEffect(() => {
    if (!activeRoom) return;
    setLoadingMessages(true);
    setRoomError('');

    supabase
      .from('together_messages')
      .select('*')
      .eq('room_id', activeRoom.id)
      .order('created_at', { ascending: true })
      .then(({ data }) => {
        setMessages(data ?? []);
        setLoadingMessages(false);
      });

    const channel = supabase
      .channel(`together-room-${activeRoom.id}`)
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'together_messages', filter: `room_id=eq.${activeRoom.id}` }, payload => {
        const msg = payload.new as TogetherMessage;
        setMessages(prev => prev.some(m => m.id === msg.id) ? prev : [...prev, msg]);
        if (msg.role === 'assistant') setClaudeThinking(false);
      })
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'together_messages', filter: `room_id=eq.${activeRoom.id}` }, payload => {
        const msg = payload.new as TogetherMessage;
        setMessages(prev => prev.map(m => m.id === msg.id ? msg : m));
      })
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'together_rooms', filter: `id=eq.${activeRoom.id}` }, payload => {
        setActiveRoom(payload.new as TogetherRoom);
      })
      .on('postgres_changes', { event: 'DELETE', schema: 'public', table: 'together_rooms', filter: `id=eq.${activeRoom.id}` }, () => {
        backToList();
      })
      .subscribe();
    messagesChannelRef.current = channel;

    return () => { supabase.removeChannel(channel); messagesChannelRef.current = null; };
  }, [activeRoom?.id]);

  useEffect(() => { chatEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages.length]);

  // ── Handlers ──────────────────────────────────────────────────────────────
  const handleCreateRoom = async () => {
    const name = newRoomName.trim();
    if (!name || !user?.id || !effectiveOrgId || creatingRoom) return;
    setCreatingRoom(true);
    const { data, error } = await supabase
      .from('together_rooms')
      .insert({
        organization_id:  effectiveOrgId,
        name,
        created_by:       user.id,
        created_by_name:  user.name,
        model:            'claude-sonnet-5',
      })
      .select('*')
      .single();
    setCreatingRoom(false);
    if (error || !data) { setRoomError('Could not create the room — please try again.'); return; }
    setNewRoomName('');
    setActiveRoom(data);
    setView('room');
  };

  const openRoom = (room: TogetherRoom) => {
    setActiveRoom(room);
    setMessages([]);
    setView('room');
  };

  const backToList = () => {
    setActiveRoom(null);
    setMessages([]);
    setView('list');
  };

  const handleSend = async () => {
    const text = input.trim();
    if (!text || !user?.id || !activeRoom || sending) return;
    if (!quotaExempt && quotaUsed >= QUOTA_TOKENS) {
      setRoomError('Quota reached — please wait for it to reset before sending more messages.');
      return;
    }
    setInput('');
    setSending(true);
    setRoomError('');

    const { error } = await supabase.from('together_messages').insert({
      room_id:     activeRoom.id,
      sender_id:   user.id,
      sender_name: user.name,
      role:        'user',
      content:     text,
    });

    setSending(false);
    if (error) { setRoomError('Message failed to send — please try again.'); return; }

    setClaudeThinking(true);
    try {
      const res = await fetch('/api/chat-room', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ room_id: activeRoom.id, user_id: user.id }),
      });
      const data = await res.json().catch(() => null);
      if (data?.error === 'quota_exceeded') {
        setRoomError('Quota reached — please wait for it to reset before sending more messages.');
        setQuotaUsed(QUOTA_TOKENS);
      } else if (!res.ok || !data?.success) {
        setRoomError("Claude couldn't reply just now — please try again.");
      }
    } catch {
      setRoomError('Network error reaching Claude — please try again.');
    } finally {
      setClaudeThinking(false);
    }
  };

  // Images are visual-only — shared straight into the room without asking
  // Claude to reply (api/chat-room.js never sees the picture itself, see
  // that file for how a share still shows up in Claude's context).
  const handleImageSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = ''; // allow re-selecting the same file later
    if (!file || !user?.id || !activeRoom || uploadingImage) return;

    if (!['image/png', 'image/jpeg', 'image/jpg', 'image/gif', 'image/webp'].includes(file.type)) {
      setRoomError('Please choose a PNG, JPEG, GIF, or WEBP image.');
      return;
    }
    if (file.size > 10 * 1024 * 1024) {
      setRoomError('That image is too large — please choose one under 10MB.');
      return;
    }

    setUploadingImage(true);
    setRoomError('');
    try {
      const { data: sessionData } = await supabase.auth.getSession();
      const accessToken = sessionData?.session?.access_token;
      if (!accessToken) throw new Error('no_session');

      const res = await fetch('/api/upload-together-asset', {
        method: 'POST',
        headers: {
          'Content-Type': file.type,
          'Authorization': `Bearer ${accessToken}`,
          'x-room-id': activeRoom.id,
          'x-filename': encodeURIComponent(file.name),
        },
        body: file,
      });
      const data = await res.json().catch(() => null);
      if (!res.ok || !data?.url) throw new Error(data?.error || 'upload_failed');

      const { error } = await supabase.from('together_messages').insert({
        room_id:     activeRoom.id,
        sender_id:   user.id,
        sender_name: user.name,
        role:        'user',
        content:     '',
        image_url:   data.url,
      });
      if (error) throw error;
    } catch {
      setRoomError('Image upload failed — please try again.');
    } finally {
      setUploadingImage(false);
    }
  };

  // ── "Our Book" — everything Claude has written plus every shared image,
  // in the order it happened. Derived straight from the messages already
  // loaded/subscribed above, so it updates live as the room does. ──────────
  const bookEntries = useMemo(
    () => messages.filter(m => !m.deleted_at && (m.role === 'assistant' || m.image_url)),
    [messages]
  );

  const handleDownloadBook = () => {
    const title = activeRoom?.name || 'Our Book';
    const body = bookEntries.map(entry => {
      if (entry.image_url) {
        const caption = entry.content?.trim()
          ? `<p style="font-size:14px;color:#666;margin-top:4px;">${escapeHtml(entry.content)}</p>` : '';
        return `<figure style="margin:24px 0;"><img src="${entry.image_url}" style="max-width:100%;border-radius:12px;" />${caption}<figcaption style="font-size:12px;color:#999;margin-top:4px;">Shared by ${escapeHtml(entry.sender_name)}</figcaption></figure>`;
      }
      return `<p style="white-space:pre-wrap;line-height:1.6;margin:16px 0;">${escapeHtml(entry.content)}</p>`;
    }).join('\n');
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title></head>
<body style="max-width:700px;margin:40px auto;font-family:Georgia,serif;padding:0 20px;">
<h1>${escapeHtml(title)}</h1>
${body}
</body></html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${title.replace(/\s+/g, '-').toLowerCase()}.html`;
    a.click();
  };

  const handleDeleteMessage = async (messageId: string) => {
    if (!isLeader || !user?.id) return;
    await supabase
      .from('together_messages')
      .update({ deleted_at: new Date().toISOString(), deleted_by: user.id })
      .eq('id', messageId);
  };

  const handleCloseRoom = async () => {
    if (!isLeader || !user?.id || !activeRoom) return;
    const { data } = await supabase
      .from('together_rooms')
      .update({ status: 'closed', closed_at: new Date().toISOString(), closed_by: user.id })
      .eq('id', activeRoom.id)
      .select('*')
      .single();
    if (data) setActiveRoom(data);
  };

  const handleDeleteRoom = async (room: TogetherRoom) => {
    if (!canDeleteRoom(room)) return;
    if (!window.confirm(`Delete "${room.name}"? This cannot be undone.`)) return;
    const { error } = await supabase.from('together_rooms').delete().eq('id', room.id);
    if (error) { setRoomError('Could not delete the room — please try again.'); return; }
    setRooms(prev => prev.filter(r => r.id !== room.id));
    if (activeRoom?.id === room.id) backToList();
  };

  const startEditingRoom = (room: TogetherRoom) => {
    setEditingRoomId(room.id);
    setEditingName(room.name);
  };

  const cancelEditingRoom = () => {
    setEditingRoomId(null);
    setEditingName('');
  };

  const handleRenameRoom = async (room: TogetherRoom) => {
    if (!canDeleteRoom(room) || renaming) return;
    const trimmed = editingName.trim();
    if (!trimmed) { cancelEditingRoom(); return; }
    if (trimmed === room.name) { cancelEditingRoom(); return; }
    setRenaming(true);
    const { data, error } = await supabase
      .from('together_rooms')
      .update({ name: trimmed })
      .eq('id', room.id)
      .select('*')
      .single();
    setRenaming(false);
    if (error) { setRoomError('Could not rename the room — please try again.'); return; }
    if (data) {
      setRooms(prev => prev.map(r => r.id === room.id ? data : r));
      if (activeRoom?.id === room.id) setActiveRoom(data);
    }
    cancelEditingRoom();
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend(); }
  };

  // ── Render ────────────────────────────────────────────────────────────────
  if (authLoading || !authChecked || !isMember) {
    return (
      <AppLayout>
        <div className="flex items-center justify-center py-24">
          <Loader2 className="animate-spin text-purple-500" size={32} />
        </div>
      </AppLayout>
    );
  }

  return (
    <AppLayout>
      <div className="max-w-4xl mx-auto">
        {view === 'list' ? (
          <div>
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 rounded-xl bg-gradient-to-br from-purple-600 to-pink-600">
                <Users size={22} className="text-white" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-gray-900">Use Claude Together</h1>
                <p className="text-sm text-gray-500">Collaborate with your group and Claude in a shared room.</p>
              </div>
            </div>

            <div className="bg-white border border-gray-200 rounded-2xl p-4 mb-6 flex gap-2">
              <input
                value={newRoomName}
                onChange={e => setNewRoomName(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleCreateRoom()}
                placeholder="Name a new room, e.g. Our Community Story"
                maxLength={100}
                className="flex-1 border border-gray-300 rounded-xl px-4 py-2 text-sm outline-none focus:ring-2 focus:ring-purple-200 focus:border-purple-400"
              />
              <button
                onClick={handleCreateRoom}
                disabled={!newRoomName.trim() || creatingRoom}
                className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-gradient-to-br from-purple-600 to-pink-600 text-white text-sm font-medium disabled:opacity-40 disabled:cursor-not-allowed hover:opacity-90 transition-opacity"
              >
                {creatingRoom ? <Loader2 size={16} className="animate-spin" /> : <Plus size={16} />}
                New Room
              </button>
            </div>

            {roomError && <p className="text-sm text-red-500 mb-4">{roomError}</p>}

            {loadingRooms ? (
              <div className="flex justify-center py-12"><Loader2 className="animate-spin text-gray-300" size={24} /></div>
            ) : rooms.length === 0 ? (
              <div className="text-center py-16 text-gray-400">
                <MessageSquare size={32} className="mx-auto mb-3 opacity-50" />
                <p>No rooms yet — start one above to begin collaborating.</p>
              </div>
            ) : (
              <div className="space-y-2">
                {rooms.map(room => (
                  <div
                    key={room.id}
                    className="bg-white border border-gray-200 rounded-xl px-4 py-3 hover:border-purple-300 hover:shadow-sm transition-all flex items-center justify-between gap-2"
                  >
                    {editingRoomId === room.id ? (
                      <>
                        <input
                          autoFocus
                          value={editingName}
                          onChange={e => setEditingName(e.target.value)}
                          onKeyDown={e => {
                            if (e.key === 'Enter') { e.preventDefault(); handleRenameRoom(room); }
                            if (e.key === 'Escape') { e.preventDefault(); cancelEditingRoom(); }
                          }}
                          maxLength={100}
                          disabled={renaming}
                          className="flex-1 min-w-0 border border-purple-300 rounded-lg px-3 py-1.5 text-sm outline-none focus:ring-2 focus:ring-purple-200"
                        />
                        <button
                          onClick={() => handleRenameRoom(room)}
                          disabled={renaming || !editingName.trim()}
                          className="p-1.5 text-gray-400 hover:text-emerald-600 disabled:opacity-40 transition-colors flex-shrink-0"
                          title="Save name"
                        >
                          {renaming ? <Loader2 size={15} className="animate-spin" /> : <Check size={15} />}
                        </button>
                        <button
                          onClick={cancelEditingRoom}
                          disabled={renaming}
                          className="p-1.5 text-gray-400 hover:text-gray-700 disabled:opacity-40 transition-colors flex-shrink-0"
                          title="Cancel"
                        >
                          <X size={15} />
                        </button>
                      </>
                    ) : (
                      <>
                        <button
                          onClick={() => openRoom(room)}
                          className="flex-1 min-w-0 text-left flex items-center justify-between gap-2"
                        >
                          <div className="min-w-0">
                            <p className="font-medium text-gray-900 truncate">{room.name}</p>
                            <p className="text-xs text-gray-400">Started by {room.created_by_name}</p>
                          </div>
                          <ArrowLeft size={16} className="text-gray-300 rotate-180 flex-shrink-0" />
                        </button>
                        {canDeleteRoom(room) && (
                          <div className="flex items-center gap-1 flex-shrink-0">
                            <button
                              onClick={() => startEditingRoom(room)}
                              className="p-1.5 text-gray-300 hover:text-purple-600 transition-colors"
                              title="Rename room"
                            >
                              <Pencil size={15} />
                            </button>
                            <button
                              onClick={() => handleDeleteRoom(room)}
                              className="p-1.5 text-gray-300 hover:text-red-500 transition-colors"
                              title="Delete room"
                            >
                              <Trash2 size={15} />
                            </button>
                          </div>
                        )}
                      </>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        ) : (
          <div className="bg-white border border-gray-200 rounded-2xl flex flex-col h-[75vh]">
            <div className="flex items-center justify-between px-5 py-3 border-b border-gray-100">
              <div className="flex items-center gap-3 min-w-0">
                <button onClick={backToList} className="p-1.5 text-gray-400 hover:text-gray-700 transition-colors flex-shrink-0">
                  <ArrowLeft size={18} />
                </button>
                <div className="min-w-0">
                  <p className="font-semibold text-gray-900 truncate">{activeRoom?.name}</p>
                  {activeRoom?.status === 'closed' && (
                    <p className="text-xs text-amber-600 flex items-center gap-1"><Lock size={11} /> Closed</p>
                  )}
                </div>
              </div>
              <div className="flex items-center gap-2 flex-shrink-0">
                <button
                  onClick={() => setShowBookModal(true)}
                  className="flex items-center gap-1.5 text-xs font-medium text-purple-600 hover:text-purple-700 border border-purple-200 hover:border-purple-300 bg-purple-50 rounded-lg px-3 py-1.5 transition-colors"
                >
                  <BookOpen size={13} /> View Book
                </button>
                {isLeader && activeRoom?.status === 'active' && (
                  <button
                    onClick={handleCloseRoom}
                    className="flex items-center gap-1.5 text-xs font-medium text-gray-500 hover:text-red-600 border border-gray-200 hover:border-red-200 rounded-lg px-3 py-1.5 transition-colors"
                  >
                    <Lock size={13} /> Close Room
                  </button>
                )}
                {activeRoom && canDeleteRoom(activeRoom) && (
                  <button
                    onClick={() => handleDeleteRoom(activeRoom)}
                    className="flex items-center gap-1.5 text-xs font-medium text-gray-500 hover:text-red-600 border border-gray-200 hover:border-red-200 rounded-lg px-3 py-1.5 transition-colors"
                  >
                    <Trash2 size={13} /> Delete Room
                  </button>
                )}
              </div>
            </div>

            <div className="flex-1 overflow-y-auto px-5 py-4 space-y-4">
              {loadingMessages ? (
                <div className="flex justify-center py-8"><Loader2 className="animate-spin text-gray-300" size={22} /></div>
              ) : messages.length === 0 ? (
                <p className="text-center text-gray-400 text-sm py-8">No messages yet — say hello to get started.</p>
              ) : (
                messages.map(msg => {
                  const isMe = msg.sender_id === user?.id;
                  const isAssistant = msg.role === 'assistant';
                  const isDeleted = !!msg.deleted_at;
                  const label = isAssistant ? 'Claude' : isMe ? 'You' : msg.sender_name;
                  return (
                    <div key={msg.id} className="group flex items-start gap-2">
                      <div className={`flex-1 rounded-2xl px-4 py-2.5 max-w-[85%] ${
                        isAssistant ? 'bg-violet-50 border border-violet-100'
                          : isMe ? 'bg-purple-600 text-white ml-auto'
                          : 'bg-gray-100'
                      }`}>
                        <p className={`text-xs font-semibold mb-0.5 flex items-center gap-1 ${isMe ? 'text-purple-100' : 'text-gray-500'}`}>
                          {isAssistant && <Bot size={12} />} {label}
                        </p>
                        {isDeleted ? (
                          <p className={`text-sm italic ${isMe ? 'text-purple-200' : 'text-gray-400'}`}>[message removed]</p>
                        ) : msg.image_url ? (
                          <div>
                            <img src={msg.image_url} alt={msg.content || 'Shared image'} className="rounded-xl max-w-full max-h-64 object-contain" />
                            {msg.content && <p className="text-sm whitespace-pre-wrap break-words mt-1.5">{msg.content}</p>}
                          </div>
                        ) : (
                          <p className="text-sm whitespace-pre-wrap break-words">{msg.content}</p>
                        )}
                      </div>
                      {isLeader && !isDeleted && !isAssistant && (
                        <button
                          onClick={() => handleDeleteMessage(msg.id)}
                          className="opacity-0 group-hover:opacity-100 p-1 text-gray-300 hover:text-red-500 transition-all flex-shrink-0 mt-1"
                          title="Remove message"
                        >
                          <Trash2 size={14} />
                        </button>
                      )}
                    </div>
                  );
                })
              )}
              {claudeThinking && (
                <div className="flex items-center gap-2 text-xs text-gray-400">
                  <Loader2 size={13} className="animate-spin" /> Claude is thinking…
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {roomError && <p className="text-xs text-red-500 px-5 pb-1">{roomError}</p>}

            {activeRoom?.status === 'closed' ? (
              <div className="px-5 py-3 border-t border-gray-100 text-center text-xs text-gray-400">
                This room is closed. History is still visible above.
              </div>
            ) : (
              <div className="flex items-end gap-2 px-5 py-3 border-t border-gray-100">
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/png,image/jpeg,image/jpg,image/gif,image/webp"
                  onChange={handleImageSelect}
                  className="hidden"
                />
                <button
                  onClick={() => fileInputRef.current?.click()}
                  disabled={uploadingImage}
                  title="Share an image"
                  className="flex-shrink-0 w-9 h-9 rounded-xl border border-gray-200 flex items-center justify-center text-gray-500 hover:text-purple-600 hover:border-purple-300 disabled:opacity-40 transition-colors"
                >
                  {uploadingImage ? <Loader2 size={15} className="animate-spin" /> : <ImageIcon size={15} />}
                </button>
                <textarea
                  value={input}
                  onChange={e => setInput(e.target.value)}
                  onKeyDown={handleKeyDown}
                  rows={1}
                  placeholder={!quotaExempt && quotaUsed >= QUOTA_TOKENS ? 'Quota reached — please wait for reset' : 'Message the room…'}
                  disabled={sending || (!quotaExempt && quotaUsed >= QUOTA_TOKENS)}
                  className="flex-1 resize-none outline-none text-sm bg-gray-50 rounded-xl px-3 py-2 max-h-32 focus:ring-2 focus:ring-purple-100"
                />
                <button
                  onClick={handleSend}
                  disabled={!input.trim() || sending || (!quotaExempt && quotaUsed >= QUOTA_TOKENS)}
                  className="flex-shrink-0 w-9 h-9 rounded-xl bg-gradient-to-br from-purple-600 to-pink-600 flex items-center justify-center text-white disabled:opacity-40 disabled:cursor-not-allowed hover:opacity-90 transition-opacity"
                >
                  {sending ? <Loader2 size={15} className="animate-spin" /> : <Send size={15} />}
                </button>
              </div>
            )}
          </div>
        )}
      </div>

      {/* ── "Our Book" artifact view — everything Claude has written plus
          every shared image, formatted like a document instead of a chat. ── */}
      {showBookModal && activeRoom && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="bg-white rounded-2xl w-full max-w-2xl max-h-[85vh] overflow-hidden shadow-2xl flex flex-col">
            <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between flex-shrink-0">
              <h2 className="text-base font-bold text-gray-900 flex items-center gap-2">
                <BookOpen size={18} className="text-purple-600" /> {activeRoom.name}
              </h2>
              <div className="flex items-center gap-2">
                <button
                  onClick={handleDownloadBook}
                  disabled={bookEntries.length === 0}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-purple-600 hover:text-purple-700 border border-purple-200 hover:border-purple-300 bg-purple-50 rounded-lg transition-colors disabled:opacity-40"
                >
                  <Download size={13} /> Download
                </button>
                <button onClick={() => setShowBookModal(false)} className="p-1 text-gray-400 hover:text-gray-700">
                  <X size={18} />
                </button>
              </div>
            </div>
            <div className="flex-1 overflow-y-auto px-8 py-6" style={{ fontFamily: 'Georgia, serif' }}>
              {bookEntries.length === 0 ? (
                <p className="text-center text-gray-400 text-sm py-12">
                  Nothing in the book yet — keep chatting with Claude and share images to build it up.
                </p>
              ) : (
                bookEntries.map(entry => (
                  <div key={entry.id} className="mb-6">
                    {entry.image_url ? (
                      <figure>
                        <img src={entry.image_url} alt={entry.content || 'Shared image'} className="rounded-xl max-w-full mx-auto" />
                        {entry.content && <p className="text-sm text-gray-600 text-center mt-2">{entry.content}</p>}
                        <figcaption className="text-xs text-gray-400 text-center mt-1">Shared by {entry.sender_name}</figcaption>
                      </figure>
                    ) : (
                      <p className="text-gray-800 leading-relaxed whitespace-pre-wrap">{entry.content}</p>
                    )}
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      )}
    </AppLayout>
  );
};

export default PlaygroundTogetherPage;
