// src/pages/PlaygroundTogetherPage.tsx
//
// "Use Claude Together" — multi-user collaborative chat rooms, restricted to
// Back to Basics Youth Education. Any org member can create/join a named
// room; leaders can remove a message (soft-delete, visible as a placeholder
// to everyone) or close a room. Assistant replies are generated by
// api/chat-room.js and inserted as a single row — all viewers see new
// messages via a Supabase Realtime subscription, not client-side streaming.

import React, { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import AppLayout from '../components/layout/AppLayout';
import { useAuth } from '../hooks/useAuth';
import { supabase } from '../lib/supabaseClient';
import { BACK_TO_BASICS_ORG_ID, isBackToBasicsMember } from '../lib/backToBasicsScope';
import { Users, Plus, Send, Trash2, Lock, Bot, ArrowLeft, Loader2, MessageSquare } from 'lucide-react';

// Matches the leader-role set enforced by RLS (together_rooms_update /
// together_messages_update_moderate) — keep in sync with the migration.
const LEADER_ROLES = new Set(['teacher', 'site_leader', 'facilitator', 'leader', 'research_lead']);

interface TogetherRoom {
  id: string;
  name: string;
  created_by: string;
  created_by_name: string;
  status: 'active' | 'closed';
  model: string;
  created_at: string;
  closed_at: string | null;
  closed_by: string | null;
}

interface TogetherMessage {
  id: string;
  room_id: string;
  sender_id: string | null;
  sender_name: string;
  role: 'user' | 'assistant';
  content: string;
  created_at: string;
  deleted_at: string | null;
  deleted_by: string | null;
}

const PlaygroundTogetherPage: React.FC = () => {
  const { user, loading: authLoading } = useAuth();
  const navigate = useNavigate();

  const [authChecked, setAuthChecked] = useState(false);
  const [isMember, setIsMember] = useState(false);

  const isLeader = !!user?.role && (LEADER_ROLES.has(user.role) || user.role === 'platform_administrator');

  const [view, setView] = useState<'list' | 'room'>('list');
  const [rooms, setRooms] = useState<TogetherRoom[]>([]);
  const [loadingRooms, setLoadingRooms] = useState(true);
  const [newRoomName, setNewRoomName] = useState('');
  const [creatingRoom, setCreatingRoom] = useState(false);

  const [activeRoom, setActiveRoom] = useState<TogetherRoom | null>(null);
  const [messages, setMessages] = useState<TogetherMessage[]>([]);
  const [loadingMessages, setLoadingMessages] = useState(false);
  const [input, setInput] = useState('');
  const [sending, setSending] = useState(false);
  const [claudeThinking, setClaudeThinking] = useState(false);
  const [roomError, setRoomError] = useState('');

  const chatEndRef = useRef<HTMLDivElement>(null);
  const roomsChannelRef = useRef<ReturnType<typeof supabase.channel> | null>(null);
  const messagesChannelRef = useRef<ReturnType<typeof supabase.channel> | null>(null);

  // ── Org-gating ────────────────────────────────────────────────────────────
  useEffect(() => {
    if (authLoading) return;
    if (!user) { navigate('/home', { replace: true }); return; }
    supabase
      .from('profiles')
      .select('organization_id, join_code_used')
      .eq('id', user.id)
      .single()
      .then(({ data }) => {
        const member = isBackToBasicsMember(data?.organization_id, data?.join_code_used);
        setIsMember(member);
        setAuthChecked(true);
        if (!member) navigate('/home', { replace: true });
      });
  }, [user, authLoading, navigate]);

  // ── Room list: fetch + realtime ──────────────────────────────────────────
  const fetchRooms = async () => {
    setLoadingRooms(true);
    const { data } = await supabase
      .from('together_rooms')
      .select('*')
      .eq('status', 'active')
      .order('updated_at', { ascending: false });
    setRooms(data ?? []);
    setLoadingRooms(false);
  };

  useEffect(() => {
    if (!authChecked || !isMember) return;
    fetchRooms();

    const channel = supabase
      .channel('together-rooms-list')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'together_rooms' }, payload => {
        const room = payload.new as TogetherRoom;
        if (room.status === 'active') setRooms(prev => [room, ...prev]);
      })
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'together_rooms' }, payload => {
        const room = payload.new as TogetherRoom;
        setRooms(prev =>
          room.status === 'active'
            ? prev.some(r => r.id === room.id) ? prev.map(r => r.id === room.id ? room : r) : [room, ...prev]
            : prev.filter(r => r.id !== room.id)
        );
      })
      .subscribe();
    roomsChannelRef.current = channel;

    return () => { supabase.removeChannel(channel); roomsChannelRef.current = null; };
  }, [authChecked, isMember]);

  // ── Room view: fetch messages + realtime ─────────────────────────────────
  useEffect(() => {
    if (!activeRoom) return;
    setLoadingMessages(true);
    setRoomError('');

    supabase
      .from('together_messages')
      .select('*')
      .eq('room_id', activeRoom.id)
      .order('created_at', { ascending: true })
      .then(({ data }) => {
        setMessages(data ?? []);
        setLoadingMessages(false);
      });

    const channel = supabase
      .channel(`together-room-${activeRoom.id}`)
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'together_messages', filter: `room_id=eq.${activeRoom.id}` }, payload => {
        const msg = payload.new as TogetherMessage;
        setMessages(prev => prev.some(m => m.id === msg.id) ? prev : [...prev, msg]);
        if (msg.role === 'assistant') setClaudeThinking(false);
      })
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'together_messages', filter: `room_id=eq.${activeRoom.id}` }, payload => {
        const msg = payload.new as TogetherMessage;
        setMessages(prev => prev.map(m => m.id === msg.id ? msg : m));
      })
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'together_rooms', filter: `id=eq.${activeRoom.id}` }, payload => {
        setActiveRoom(payload.new as TogetherRoom);
      })
      .subscribe();
    messagesChannelRef.current = channel;

    return () => { supabase.removeChannel(channel); messagesChannelRef.current = null; };
  }, [activeRoom?.id]);

  useEffect(() => { chatEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages.length]);

  // ── Handlers ──────────────────────────────────────────────────────────────
  const handleCreateRoom = async () => {
    const name = newRoomName.trim();
    if (!name || !user?.id || creatingRoom) return;
    setCreatingRoom(true);
    const { data, error } = await supabase
      .from('together_rooms')
      .insert({
        organization_id:  BACK_TO_BASICS_ORG_ID,
        name,
        created_by:       user.id,
        created_by_name:  user.name,
        model:            'claude-sonnet-5',
      })
      .select('*')
      .single();
    setCreatingRoom(false);
    if (error || !data) { setRoomError('Could not create the room — please try again.'); return; }
    setNewRoomName('');
    setActiveRoom(data);
    setView('room');
  };

  const openRoom = (room: TogetherRoom) => {
    setActiveRoom(room);
    setMessages([]);
    setView('room');
  };

  const backToList = () => {
    setActiveRoom(null);
    setMessages([]);
    setView('list');
  };

  const handleSend = async () => {
    const text = input.trim();
    if (!text || !user?.id || !activeRoom || sending) return;
    setInput('');
    setSending(true);
    setRoomError('');

    const { error } = await supabase.from('together_messages').insert({
      room_id:     activeRoom.id,
      sender_id:   user.id,
      sender_name: user.name,
      role:        'user',
      content:     text,
    });

    setSending(false);
    if (error) { setRoomError('Message failed to send — please try again.'); return; }

    setClaudeThinking(true);
    try {
      const res = await fetch('/api/chat-room', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ room_id: activeRoom.id, user_id: user.id }),
      });
      const data = await res.json().catch(() => null);
      if (!res.ok || !data?.success) setRoomError("Claude couldn't reply just now — please try again.");
    } catch {
      setRoomError('Network error reaching Claude — please try again.');
    } finally {
      setClaudeThinking(false);
    }
  };

  const handleDeleteMessage = async (messageId: string) => {
    if (!isLeader || !user?.id) return;
    await supabase
      .from('together_messages')
      .update({ deleted_at: new Date().toISOString(), deleted_by: user.id })
      .eq('id', messageId);
  };

  const handleCloseRoom = async () => {
    if (!isLeader || !user?.id || !activeRoom) return;
    const { data } = await supabase
      .from('together_rooms')
      .update({ status: 'closed', closed_at: new Date().toISOString(), closed_by: user.id })
      .eq('id', activeRoom.id)
      .select('*')
      .single();
    if (data) setActiveRoom(data);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend(); }
  };

  // ── Render ────────────────────────────────────────────────────────────────
  if (authLoading || !authChecked || !isMember) {
    return (
      <AppLayout>
        <div className="flex items-center justify-center py-24">
          <Loader2 className="animate-spin text-purple-500" size={32} />
        </div>
      </AppLayout>
    );
  }

  return (
    <AppLayout>
      <div className="max-w-4xl mx-auto">
        {view === 'list' ? (
          <div>
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 rounded-xl bg-gradient-to-br from-purple-600 to-pink-600">
                <Users size={22} className="text-white" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-gray-900">Use Claude Together</h1>
                <p className="text-sm text-gray-500">Collaborate with your group and Claude in a shared room.</p>
              </div>
            </div>

            <div className="bg-white border border-gray-200 rounded-2xl p-4 mb-6 flex gap-2">
              <input
                value={newRoomName}
                onChange={e => setNewRoomName(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleCreateRoom()}
                placeholder="Name a new room, e.g. Our Community Story"
                maxLength={100}
                className="flex-1 border border-gray-300 rounded-xl px-4 py-2 text-sm outline-none focus:ring-2 focus:ring-purple-200 focus:border-purple-400"
              />
              <button
                onClick={handleCreateRoom}
                disabled={!newRoomName.trim() || creatingRoom}
                className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-gradient-to-br from-purple-600 to-pink-600 text-white text-sm font-medium disabled:opacity-40 disabled:cursor-not-allowed hover:opacity-90 transition-opacity"
              >
                {creatingRoom ? <Loader2 size={16} className="animate-spin" /> : <Plus size={16} />}
                New Room
              </button>
            </div>

            {roomError && <p className="text-sm text-red-500 mb-4">{roomError}</p>}

            {loadingRooms ? (
              <div className="flex justify-center py-12"><Loader2 className="animate-spin text-gray-300" size={24} /></div>
            ) : rooms.length === 0 ? (
              <div className="text-center py-16 text-gray-400">
                <MessageSquare size={32} className="mx-auto mb-3 opacity-50" />
                <p>No rooms yet — start one above to begin collaborating.</p>
              </div>
            ) : (
              <div className="space-y-2">
                {rooms.map(room => (
                  <button
                    key={room.id}
                    onClick={() => openRoom(room)}
                    className="w-full text-left bg-white border border-gray-200 rounded-xl px-4 py-3 hover:border-purple-300 hover:shadow-sm transition-all flex items-center justify-between"
                  >
                    <div>
                      <p className="font-medium text-gray-900">{room.name}</p>
                      <p className="text-xs text-gray-400">Started by {room.created_by_name}</p>
                    </div>
                    <ArrowLeft size={16} className="text-gray-300 rotate-180" />
                  </button>
                ))}
              </div>
            )}
          </div>
        ) : (
          <div className="bg-white border border-gray-200 rounded-2xl flex flex-col h-[75vh]">
            <div className="flex items-center justify-between px-5 py-3 border-b border-gray-100">
              <div className="flex items-center gap-3 min-w-0">
                <button onClick={backToList} className="p-1.5 text-gray-400 hover:text-gray-700 transition-colors flex-shrink-0">
                  <ArrowLeft size={18} />
                </button>
                <div className="min-w-0">
                  <p className="font-semibold text-gray-900 truncate">{activeRoom?.name}</p>
                  {activeRoom?.status === 'closed' && (
                    <p className="text-xs text-amber-600 flex items-center gap-1"><Lock size={11} /> Closed</p>
                  )}
                </div>
              </div>
              {isLeader && activeRoom?.status === 'active' && (
                <button
                  onClick={handleCloseRoom}
                  className="flex items-center gap-1.5 text-xs font-medium text-gray-500 hover:text-red-600 border border-gray-200 hover:border-red-200 rounded-lg px-3 py-1.5 transition-colors flex-shrink-0"
                >
                  <Lock size={13} /> Close Room
                </button>
              )}
            </div>

            <div className="flex-1 overflow-y-auto px-5 py-4 space-y-4">
              {loadingMessages ? (
                <div className="flex justify-center py-8"><Loader2 className="animate-spin text-gray-300" size={22} /></div>
              ) : messages.length === 0 ? (
                <p className="text-center text-gray-400 text-sm py-8">No messages yet — say hello to get started.</p>
              ) : (
                messages.map(msg => {
                  const isMe = msg.sender_id === user?.id;
                  const isAssistant = msg.role === 'assistant';
                  const isDeleted = !!msg.deleted_at;
                  const label = isAssistant ? 'Claude' : isMe ? 'You' : msg.sender_name;
                  return (
                    <div key={msg.id} className="group flex items-start gap-2">
                      <div className={`flex-1 rounded-2xl px-4 py-2.5 max-w-[85%] ${
                        isAssistant ? 'bg-violet-50 border border-violet-100'
                          : isMe ? 'bg-purple-600 text-white ml-auto'
                          : 'bg-gray-100'
                      }`}>
                        <p className={`text-xs font-semibold mb-0.5 flex items-center gap-1 ${isMe ? 'text-purple-100' : 'text-gray-500'}`}>
                          {isAssistant && <Bot size={12} />} {label}
                        </p>
                        {isDeleted ? (
                          <p className={`text-sm italic ${isMe ? 'text-purple-200' : 'text-gray-400'}`}>[message removed]</p>
                        ) : (
                          <p className="text-sm whitespace-pre-wrap break-words">{msg.content}</p>
                        )}
                      </div>
                      {isLeader && !isDeleted && !isAssistant && (
                        <button
                          onClick={() => handleDeleteMessage(msg.id)}
                          className="opacity-0 group-hover:opacity-100 p-1 text-gray-300 hover:text-red-500 transition-all flex-shrink-0 mt-1"
                          title="Remove message"
                        >
                          <Trash2 size={14} />
                        </button>
                      )}
                    </div>
                  );
                })
              )}
              {claudeThinking && (
                <div className="flex items-center gap-2 text-xs text-gray-400">
                  <Loader2 size={13} className="animate-spin" /> Claude is thinking…
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {roomError && <p className="text-xs text-red-500 px-5 pb-1">{roomError}</p>}

            {activeRoom?.status === 'closed' ? (
              <div className="px-5 py-3 border-t border-gray-100 text-center text-xs text-gray-400">
                This room is closed. History is still visible above.
              </div>
            ) : (
              <div className="flex items-end gap-2 px-5 py-3 border-t border-gray-100">
                <textarea
                  value={input}
                  onChange={e => setInput(e.target.value)}
                  onKeyDown={handleKeyDown}
                  rows={1}
                  placeholder="Message the room…"
                  disabled={sending}
                  className="flex-1 resize-none outline-none text-sm bg-gray-50 rounded-xl px-3 py-2 max-h-32 focus:ring-2 focus:ring-purple-100"
                />
                <button
                  onClick={handleSend}
                  disabled={!input.trim() || sending}
                  className="flex-shrink-0 w-9 h-9 rounded-xl bg-gradient-to-br from-purple-600 to-pink-600 flex items-center justify-center text-white disabled:opacity-40 disabled:cursor-not-allowed hover:opacity-90 transition-opacity"
                >
                  {sending ? <Loader2 size={15} className="animate-spin" /> : <Send size={15} />}
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </AppLayout>
  );
};

export default PlaygroundTogetherPage;
